//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Bill()
        {
            this.Moneys = new HashSet<Money>();
        }
    
        public int Id { get; set; }
        public string Month { get; set; }
        public Nullable<int> Home_rent { get; set; }
        public Nullable<int> Water_bill { get; set; }
        public Nullable<int> Dirty_bill { get; set; }
        public Nullable<int> Service_Charge { get; set; }
        public Nullable<int> Gas_bill { get; set; }
        public Nullable<int> Other_bill { get; set; }
        public Nullable<int> Prevous_bill { get; set; }
        public Nullable<int> Total_bill { get; set; }
        public Nullable<int> Give_money { get; set; }
        public Nullable<int> Rest_off_bill { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int login_id { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual ICollection<Money> Moneys { get; set; }
    }
}
