//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Entity_Layer.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Api_Home_RentEntities : DbContext
    {
        public Api_Home_RentEntities()
            : base("name=Api_Home_RentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill> Bills { get; set; }
        public DbSet<Cost> Costs { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Money> Moneys { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Tanent> Tanents { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
